---
- name: Deploy docker images
  hosts: local
  
  gather_facts: yes
  become: yes
  tasks:
    - name: Copy Docker Compose file from host machine to remote host
      copy:
        src: ./docker-compose.yml
        dest: ./



    # Now we actually run the Docker containers 
    # Detached mode is required, otherwise Jenkins build never exits
    # even though the docker-compose up command has successfully executed
    - name: Run the pulled Docker images in detached mode
      command: docker-compose up -d --build

    - name: Prune the dangling Docker images
      command: /opt/homebrew/bin/docker image prune --force